### ISSUE TITLE
Library fails to parse Teensy Audio example waves: SDTEST1.WAV

### ISSUE THREAD

**Issue by atoktoto** [newdigate/teensy-variable-playback#42]
I though this might be worth flagging as these are almost "known good" and once can expect to already have them on the SD card after going through the Teensy Audio Library tutorial or hardware tests.

The error I'm getting is (same for all 4 files):
`expected data... (was 537263808)`

**Comment by newdigate** [comment]
oh. I’ll take a look on tuesday hopefully. 

Thanks for letting me know…. :P

**Comment by newdigate** [comment]
Hi Andrei, I have this feature branch, but I have not tested it... Im hoping the teensy reference wavs should now read ok...

https://github.com/newdigate/teensy-variable-playback/tree/feature/wav_info_tags

Could you check it out and let me know if its working? Otherwise I will spend some time testing it in the next week or so -- Unfortunately, I have limited time right now, too many things going on :)

**Comment by newdigate** [comment]
scratch that, still needs some work....

**Comment by newdigate** [comment]
Updated the library to skip over any riff tags in the wav header now... Done some testing, seems good... (merged to main, deleted feature branch).
